apiVersion: v1
kind: ConfigMap
metadata:
  name: back-office-config-file
data:
  default.conf: |
    server {
    listen       80;
    location / {
        alias   /usr/share/nginx/html/;
        rewrite ^(.*)\/\/([a-zA-Z0-9-.:]*)\/?(.*)$ $2/$3 permanent;
        try_files $uri $uri/ index.html;
    }
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
    }